### ISSUE TITLE
add integration diectly on the remote

### ISSUE THREAD

**Issue by run51** [kennymc-c/ucr2-integration-requests#3]
hello 

i have bet remote firmware and i want to upload directly your plugin in the remote
Can you compil a version compatible with ulpoad please

thank you

**Comment by kennymc-c** [comment]
I just released a version that includes that archive file: [Release v0.3.0 · kennymc-c/ucr2-integration-requests · GitHub](https://github.com/kennymc-c/ucr2-integration-requests/releases/tag/v0.3.0)
