### ISSUE TITLE
Send basic text over TCP 

### ISSUE THREAD

**Issue by mitzsch** [kennymc-c/ucr2-integration-requests#5]
Really appreciate this integration. Thanks!

Is it possible to just send basic text without a header or anything else with this integration? Or can this be added?

For my HTPC I want to use this https://github.com/moefh/win-remote-control software. It accepts text input over TCP/IP and translates it into key inputs.

I wrote a simple Python script that can send basic text... (No idea if this is useful.)
https://github.com/mitzsch/scriptsandotherstuff/blob/main/Windows/win-remote-control/textovertcp.py

`python textovertcp.py IP/Hostname Port keyinput`

Would be awesome if this functionality (basic text over TCP) could be added to this integration! Thanks!

**Comment by kennymc-c** [comment]
Wouldn't be Bluetooth a much better way to control the HTPC?

**Comment by mitzsch** [comment]
The problem with Bluetooth I have is the slow "wake-up" / "connected state"... With the IP control it's a small .exe that automatically starts with Windows and is ready to go - no huge delay there - that's why I would prefer the IP solution (+ the htpc does not need a BT dongle)

**Comment by kennymc-c** [comment]
Are there any other tools or devices that can be controlled with text over tcp?
The problem is that this could be a very specific and limited use case only working with the win-remote-control tool while other parts of this integration can used more universal. This integration should not be tailored to any specific use cases but rather act as universal swiss army knife that can be used without much modification in a lot of use cases.

**Comment by mitzsch** [comment]
>Are there any other tools or devices that can be controlled with text over tcp?

I have heard that some IoT devices actually accept commands via text over ip/tcp - although I have not tested this. I know that some ESP projects are built on top of this functionality and can be controlled via text commands.

No idea if this is enough to bring in this functionality. Not sure how much work it would be.

**Comment by kennymc-c** [comment]
I've just released a new version that includes a text over TCP entity:
https://github.com/kennymc-c/ucr2-integration-requests/releases/tag/v0.5.0

**Comment by mitzsch** [comment]
Awesome, thanks!!!! :)
